/**
 * @file
 *
 * Define SAMPLE App Events IDs
 */

#ifndef SAMPLE_APP_EVENTS_H
#define SAMPLE_APP_EVENTS_H

#define SAMPLE_APP_RESERVED_EID          0
#define SAMPLE_APP_STARTUP_INF_EID       1
#define SAMPLE_APP_COMMAND_ERR_EID       2
#define SAMPLE_APP_COMMANDNOP_INF_EID    3
#define SAMPLE_APP_COMMANDRST_INF_EID    4
#define SAMPLE_APP_INVALID_MSGID_ERR_EID 5
#define SAMPLE_APP_LEN_ERR_EID           6
#define SAMPLE_APP_PIPE_ERR_EID          7

#define SAMPLE_APP_EVENT_COUNTS 7

#endif /* SAMPLE_APP_EVENTS_H */
