name: Build and Run

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  schedule:
    # 10:45 PM UTC every Sunday
    - cron:  '45 22 * * 0'

permissions:
  contents: read

jobs:
  build-run:
    name: Build and run with startup msg verification
    uses: nasa/cFS/.github/workflows/build-run-app-reusable.yml@dev
    with:
      dependency: nasa/sample_lib
      app-entrypoint-suffix: Main